%%
%% Autogenerated by Thrift Compiler (0.7.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(course_types).

-include("course_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('phone') ->
  {struct, [{1, i32}, {2, string}, {3, i32}]}
;

struct_info('person') ->
  {struct, [{1, i32}, {2, string}, {3, string}, {4, string}, {5, {list, {struct, {'course_types', 'phone'}}}}]}
;

struct_info('course') ->
  {struct, [{1, i32}, {2, string}, {3, string}, {4, {struct, {'course_types', 'person'}}}, {5, string}, {6, {list, {struct, {'course_types', 'person'}}}}]}
;

struct_info('courseNotFound') ->
  {struct, [{1, string}]}
;

struct_info('unacceptableCourse') ->
  {struct, [{1, string}]}
;

struct_info('i am a dummy struct') -> undefined.

struct_info_ext('phone') ->
  {struct, [{1, undefined, i32, 'id', undefined}, {2, undefined, string, 'number', undefined}, {3, undefined, i32, 'type', undefined}]}
;

struct_info_ext('person') ->
  {struct, [{1, undefined, i32, 'id', undefined}, {2, undefined, string, 'firstName', undefined}, {3, undefined, string, 'lastName', undefined}, {4, undefined, string, 'email', undefined}, {5, undefined, {list, {struct, {'course_types', 'phone'}}}, 'phones', []}]}
;

struct_info_ext('course') ->
  {struct, [{1, undefined, i32, 'id', undefined}, {2, undefined, string, 'number', undefined}, {3, undefined, string, 'name', undefined}, {4, undefined, {struct, {'course_types', 'person'}}, 'instructor', #person{}}, {5, undefined, string, 'roomNumber', undefined}, {6, undefined, {list, {struct, {'course_types', 'person'}}}, 'students', []}]}
;

struct_info_ext('courseNotFound') ->
  {struct, [{1, undefined, string, 'message', undefined}]}
;

struct_info_ext('unacceptableCourse') ->
  {struct, [{1, undefined, string, 'message', undefined}]}
;

struct_info_ext('i am a dummy struct') -> undefined.

