%%
%% Autogenerated by Thrift Compiler (0.7.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(courseService_thrift).
-behaviour(thrift_service).


-include("courseService_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info('i am a dummy struct') -> undefined.
%%% interface
% getCourseInventory(This)
function_info('getCourseInventory', params_type) ->
  {struct, []}
;
function_info('getCourseInventory', reply_type) ->
  {list, string};
function_info('getCourseInventory', exceptions) ->
  {struct, []}
;
% getCourse(This, CourseNumber)
function_info('getCourse', params_type) ->
  {struct, [{1, string}]}
;
function_info('getCourse', reply_type) ->
  {struct, {'course_types', 'course'}};
function_info('getCourse', exceptions) ->
  {struct, [{1, {struct, {'course_types', 'courseNotFound'}}}]}
;
% addCourse(This, Course)
function_info('addCourse', params_type) ->
  {struct, [{1, {struct, {'course_types', 'course'}}}]}
;
function_info('addCourse', reply_type) ->
  {struct, []};
function_info('addCourse', exceptions) ->
  {struct, [{1, {struct, {'course_types', 'unacceptableCourse'}}}]}
;
% deleteCourse(This, CourseNumber)
function_info('deleteCourse', params_type) ->
  {struct, [{1, string}]}
;
function_info('deleteCourse', reply_type) ->
  {struct, []};
function_info('deleteCourse', exceptions) ->
  {struct, [{1, {struct, {'course_types', 'courseNotFound'}}}]}
;
function_info(_Func, _Info) -> no_function.

