/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "course_constants.h"

namespace thrift { namespace client {

const courseConstants g_course_constants;

courseConstants::courseConstants() {
}

}} // namespace

