// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "CourseService.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace thrift::client;

class CourseServiceHandler : virtual public CourseServiceIf {
 public:
  CourseServiceHandler() {
    // Your initialization goes here
  }

  void getCourseInventory(std::vector<std::string> & _return) {
    // Your implementation goes here
    printf("getCourseInventory\n");
  }

  void getCourse(Course& _return, const std::string& courseNumber) {
    // Your implementation goes here
    printf("getCourse\n");
  }

  void addCourse(const Course& course) {
    // Your implementation goes here
    printf("addCourse\n");
  }

  void deleteCourse(const std::string& courseNumber) {
    // Your implementation goes here
    printf("deleteCourse\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<CourseServiceHandler> handler(new CourseServiceHandler());
  shared_ptr<TProcessor> processor(new CourseServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

