/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef course_CONSTANTS_H
#define course_CONSTANTS_H

#include "course_types.h"

namespace thrift { namespace client {

class courseConstants {
 public:
  courseConstants();

};

extern const courseConstants g_course_constants;

}} // namespace

#endif
